services:
  - type: web
    name: laravel-backend
    runtime: docker
    plan: free
    dockerfilePath: Dockerfile
    autoDeploy: true
    envVars:
      - key: APP_ENV
        value: "production"
      - key: APP_DEBUG
        value: "false"
      - key: APP_KEY
        sync: false
      - key: MAIL_MAILER
        value: "smtp"
      - key: MAIL_HOST
        value: "sandbox.smtp.mailtrap.io"
      - key: MAIL_PORT
        value: "2525"
      - key: MAIL_USERNAME
        sync: false
      - key: MAIL_PASSWORD
        sync: false
      - key: MAIL_ENCRYPTION
        value: "tls"
      - key: MAIL_FROM_ADDRESS
        value: "no-reply@facturacion.com"
      - key: MAIL_FROM_NAME
        value: "FacturaFácil"
